version: '3.8'

services:
  db:
    image: mysql:5.6
    container_name: poc-ms-hexagonal-db
    restart: always
    tty: true
    volumes:
      - ./docker/data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=pocmshexagonal
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
    networks:
     - challenge-exacta
#  exacta-works-app:
#    image: cflsena/challenge-exacta-works
#    build:
#      context: ./
#      dockerfile: ./Dockerfile
#      args:
#        PROFILES: default
#    container_name: challenge-exacta-works-app
#    entrypoint: dockerize -wait tcp://db:3306 -timeout 40s ./entrypoint.sh
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://challenge-exacta-works-db:3306/exactadb?createDatabaseIfNotExist=true
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: root
#    networks:
#     - challenge-exacta

networks:
  challenge-exacta:
    name: poc-ms-hexagonal
    driver: bridge