server:
  error:
    include-stacktrace: on_param
  servlet:
    context-path: /poc-ms-hexagonal/api/v1/
  port: 8080

spring:
  profiles:
    - default
  datasource:
    initialize: false
    url: jdbc:mysql://localhost:3306/pocmshexagonal?createDatabaseIfNotExist=true
    username: root
    password: root
    jpa:
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      generate-ddl: true
      hibernate:
        ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.xml
    default_schema: "pocmshexagonal"
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
    properties:
      org:
        hibernate:
          format_sql: false
          envers:
            audit_table_suffix: "_aud"
            revision_field_name: revision
            revision_type_field_name: revision_type
            store_data_at_delete: true
            default_schema: "pocmshexagonal"

springdoc:
  swagger-ui:
    path: /documentation.html