server:
  error:
    include-stacktrace: on_param
  servlet:
    context-path: /poc-ms-hexagonal/api/v1/
  port: 8080

spring:
  profiles:
    - default
  datasource:
    initialize: false
    url: jdbc:mysql://localhost:3306/pocmshexagonal?createDatabaseIfNotExist=true
    username: root
    password: root
    jpa:
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      generate-ddl: true
      hibernate:
        ddl-auto: update
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.xml
    default_schema: "pocmshexagonal"

springdoc:
  swagger-ui:
    path: /documentation.html